language: node_js
sudo: false # faster builds

node_js:
  - "4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - rvm install ruby

before_script:
  - gem install sass
  - npm install -g grunt-cli
  - npm install --dev

script:
  - npm test
